### PR TITLE
fix: fix crontab exception in a basic docker container

### LINKED ISSUE #55: fix crontab exception in a basic docker container
on a basic docker container, there is no crontab command, so we have an ugly exception during startup

### PR DESCRIPTION
**Pull request by thebaptiste**
(exception is normal on continuous integration with docker)

close #55

### CODE REVIEW

**Comment by thebaptiste** [comment]
I fixed the crontab exception at mfxxx.start, but I still have to fix it at mfxxx.stop...

File: adm/_make_and_install_crontab.sh [hunk 1]
```diff
@@ -19,10 +19,9 @@ echo_ok
...
 echo -n "- Installing crontab file..."
 echo_running
-deploycron_file "${MODULE_RUNTIME_HOME}/tmp/config_auto/crontab"
+deploycron_file "${MODULE_RUNTIME_HOME}/tmp/config_auto/crontab" > /dev/null 2>&1
 if test $? -eq 0; then
     echo_ok
 else
-    echo_nok
-    exit 1
+    echo_warning "Can't install crontab file (normal if you are in continuous integration with docker)"
```
Comment (thefab) [inline adm/_make_and_install_crontab.sh]: This line is too long. I propose instead:
```bash
echo_nok "(can't install)"
```

I propose `echo_nok` and not `echo_warning` because of test introduced in previous comment.


```

File: adm/_make_and_install_crontab.sh [hunk 2]
```diff
@@ -19,10 +19,9 @@ echo_ok
 
 echo -n "- Installing crontab file..."
 echo_running
```
Comment (thefab) [inline adm/_make_and_install_crontab.sh]: I would add a test like that just after this line:

```bash
if hash crontab 2>/dev/null; then
    [...] # the existing block of code (deploycron_file... and corresponding tests)
else
    echo_warning "(no crontab installed)"
fi
```

File: adm/_make_and_install_crontab.sh (hunk 1 above)
Comment (thefab) [inline adm/_make_and_install_crontab.sh]: it would be interesting to add a similar test to `mfxxx.status`:

- if the crontab command does not exist => warning
- if the crontab command exists AND if the crontab is empty => nok (with a !=0 return code)

**Comment by thebaptiste** [comment]
I have done the requested changes and fixed also _uninstall_crontab.sh
For mfxxx.status, I think it is an issue for mfext

File: adm/_make_and_install_crontab.sh [hunk 3]
```diff
@@ -19,10 +19,16 @@ echo_ok
...
-deploycron_file "${MODULE_RUNTIME_HOME}/tmp/config_auto/crontab"
-if test $? -eq 0; then
-    echo_ok
+
+if hash crontab 2>/dev/null; then
+    deploycron_file "${MODULE_RUNTIME_HOME}/tmp/config_auto/crontab" >/dev/null 2>"${MODULE_RUNTIME_HOME}/tmp/deploycron_errors.$$"
```
Comment (thefab) [inline adm/_make_and_install_crontab.sh]:
```suggestion
    deploycron_file "${MODULE_RUNTIME_HOME}/tmp/config_auto/crontab" >"${MODULE_RUNTIME_HOME}/tmp/deploycron_errors.$$" 2>&1"
```
